{
    "openapi": "3.0.0",
    "info": {
        "title": "AniDB API Documentation",
        "version": "1.0"
    },
    "paths": {
        "/api/auth/register": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "User Registration",
                "operationId": "31cfdf7ad0b73495ed2b7bb54e9d8a54",
                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "email"
                        },
                        "example": "user@mail.com"
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "password"
                    },
                    {
                        "name": "password_confirmation",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "password"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "status": {
                                            "type": "number"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "status": 200,
                                    "message": "Success",
                                    "data": {
                                        "token": "alphanumeric token"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Failed"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "User Login",
                "operationId": "d7cbb3ac96888b0e21dcf8ee1845fe40",
                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "email"
                        },
                        "example": "user@mail.com"
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "password"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "status": {
                                            "type": "number"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "status": 200,
                                    "message": "Success",
                                    "data": {
                                        "token": "alphanumeric token"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid Form or Invalid Credentials",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "status": {
                                            "type": "number"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "examples": {
                                    "InvalidForm": {
                                        "summary": "Invalid Form",
                                        "value": {
                                            "status": 400,
                                            "data": {
                                                "email": [
                                                    [
                                                        "The email field is required."
                                                    ]
                                                ],
                                                "password": [
                                                    [
                                                        "The password field is required."
                                                    ]
                                                ]
                                            }
                                        }
                                    },
                                    "InvalidCredentials": {
                                        "summary": "Invalid Credentials",
                                        "value": {
                                            "status": 400,
                                            "message": "username or password is invalid"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "User Logout",
                "operationId": "7bdaf2cc85f771edf0ea8b95bb8dbac1",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Success"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/auth/user": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get User",
                "operationId": "b8424f088ab85f004529540f377aa681",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "id": {
                                            "type": "number"
                                        },
                                        "email": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "id": 1,
                                    "email": "test@mail.com"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/buckets": {
            "get": {
                "tags": [
                    "Bucket"
                ],
                "summary": "Get All Buckets",
                "operationId": "79ee2ec8f2dff7429a502d499c7ed000",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Bucket"
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/catalogs": {
            "get": {
                "tags": [
                    "Catalog"
                ],
                "summary": "Get All Catalog",
                "operationId": "bf7d3c3af4d71538d00b0df849f3d908",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Catalog"
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Catalog"
                ],
                "summary": "Add a Catalog",
                "operationId": "8d851d66dad56921006fe15cca087444",
                "parameters": [
                    {
                        "name": "year",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "example": "2020"
                    },
                    {
                        "name": "season",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "Winter",
                                "Spring",
                                "Summer",
                                "Fall"
                            ]
                        },
                        "example": "Winter"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Success"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/catalogs/{catalog_id}": {
            "get": {
                "tags": [
                    "Catalog"
                ],
                "summary": "Get Partials in Catalog",
                "operationId": "4b0774dc654f92416d46f3d7a10d20b4",
                "parameters": [
                    {
                        "name": "catalog_id",
                        "in": "path",
                        "description": "Catalog ID",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "example": "e9597119-8452-4f2b-96d8-f2b1b1d2f158"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Partial"
                                            }
                                        },
                                        "stats": {
                                            "$ref": "#/components/schemas/Catalog"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Catalog"
                ],
                "summary": "Edit a Catalog",
                "operationId": "0eab08efecfd0eb04f1f6805da8af369",
                "parameters": [
                    {
                        "name": "catalog_id",
                        "in": "path",
                        "description": "Catalog ID",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "example": "e9597119-8452-4f2b-96d8-f2b1b1d2f158"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Success"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Catalog"
                ],
                "summary": "Delete a Catalog",
                "operationId": "cfdc75fe92bd8e71c989ed0696b8a53f",
                "parameters": [
                    {
                        "name": "catalog_id",
                        "in": "path",
                        "description": "Catalog ID",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "example": "e9597119-8452-4f2b-96d8-f2b1b1d2f158"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Success"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/groups": {
            "get": {
                "tags": [
                    "Group"
                ],
                "summary": "Get All Groups",
                "operationId": "74f97965cba29ff042644d03ab580adc",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Group"
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Group"
                ],
                "summary": "Add a Group",
                "operationId": "d5e58c0df5e02a3de23c70700551aa64",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "Sample Group Name"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Group"
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/groups/names": {
            "get": {
                "tags": [
                    "Group"
                ],
                "summary": "Get All Group Names",
                "operationId": "53fbdf770508b509a82ce8241e563ba9",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/groups/{group_id}": {
            "put": {
                "tags": [
                    "Group"
                ],
                "summary": "Edit a Group",
                "operationId": "c6d4c44e7f3880c4e941de9d7f9ec40c",
                "parameters": [
                    {
                        "name": "group_id",
                        "in": "path",
                        "description": "Group ID",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "example": "e9597119-8452-4f2b-96d8-f2b1b1d2f158"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Success"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Group"
                ],
                "summary": "Delete a Group",
                "operationId": "89ce3046c99740e998e236b35854b8da",
                "parameters": [
                    {
                        "name": "group_id",
                        "in": "path",
                        "description": "Group ID",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "example": "e9597119-8452-4f2b-96d8-f2b1b1d2f158"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Success"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/logs": {
            "get": {
                "tags": [
                    "Logs"
                ],
                "summary": "Get All Logs",
                "operationId": "6897ba59c8c4db4a9466e5df41a9c4e0",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Log"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/components/schemas/Pagination"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        },
        "/api/qualities": {
            "get": {
                "tags": [
                    "Dropdowns"
                ],
                "summary": "Get All Qualities",
                "operationId": "3d28e8a72e59e561df48780d83c44b6d",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Quality"
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Unauthorized"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "token": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "Success": {
                "title": "Default Success Response",
                "properties": {
                    "status": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "status": "200",
                    "message": "Success"
                }
            },
            "Unauthorized": {
                "title": "401 Forbidden Error Response",
                "properties": {
                    "status": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "status": "401",
                    "message": "Unauthorized"
                }
            },
            "Failed": {
                "title": "500 Internal Server Error Response",
                "properties": {
                    "status": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "status": "500",
                    "message": "Failed"
                }
            },
            "Pagination": {
                "title": "Pagination Meta",
                "properties": {
                    "meta": {
                        "properties": {
                            "page": {
                                "type": "integer",
                                "format": "int32",
                                "minimum": 1
                            },
                            "limit": {
                                "type": "integer",
                                "format": "int32",
                                "minimum": 1
                            },
                            "total": {
                                "type": "integer",
                                "format": "int32",
                                "minimum": 1
                            },
                            "has_next": {
                                "type": "boolean"
                            }
                        },
                        "type": "object"
                    }
                },
                "type": "object",
                "example": {
                    "meta": {
                        "page": 1,
                        "limit": 30,
                        "total": 5,
                        "has_next": true
                    }
                }
            },
            "Bucket": {
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "from": {
                        "type": "string"
                    },
                    "to": {
                        "type": "string"
                    },
                    "size": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "type": "object",
                "example": {
                    "id": 1,
                    "from": "a",
                    "to": "d",
                    "size": 2000339066880
                }
            },
            "Catalog": {
                "properties": {
                    "id": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "year": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "season": {
                        "type": "string",
                        "enum": [
                            "Winter",
                            "Spring",
                            "Summer",
                            "Fall"
                        ]
                    }
                },
                "type": "object",
                "example": {
                    "id": "e9597119-8452-4f2b-96d8-f2b1b1d2f158",
                    "year": 2020,
                    "season": "Winter"
                }
            },
            "Group": {
                "properties": {
                    "uuid": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "uuid": "e9597119-8452-4f2b-96d8-f2b1b1d2f158",
                    "name": "Sample Group Name"
                }
            },
            "Log": {
                "properties": {
                    "id": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "table_changed": {
                        "type": "string"
                    },
                    "id_changed": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "action": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    }
                },
                "type": "object",
                "example": {
                    "id": "9ef81943-78f0-4d1c-a831-a59fb5af339c",
                    "table_changed": "marathon",
                    "id_changed": 1,
                    "description": "title changed from 'old' to 'new'",
                    "action": "add",
                    "created_at": "2020-01-01 00:00:00"
                }
            },
            "Partial": {
                "properties": {
                    "id": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "title": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "string",
                        "enum": [
                            "High",
                            "Normal",
                            "Low"
                        ]
                    }
                },
                "type": "object",
                "example": {
                    "id": "e9597119-8452-4f2b-96d8-f2b1b1d2f158",
                    "title": "Sample Title",
                    "priority": "High"
                }
            },
            "Quality": {
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "quality": {
                        "type": "string",
                        "enum": [
                            "4K 2160",
                            "FHD 1080p",
                            "HD 720p",
                            "HQ 480p",
                            "LQ 360p"
                        ]
                    }
                },
                "type": "object",
                "example": {
                    "id": 1,
                    "quality": "4K 2160p"
                }
            }
        },
        "securitySchemes": {
            "token": {
                "type": "http",
                "description": "Login with email and password to get the authentication token",
                "name": "Authorization",
                "in": "header",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    }
}